[[constraint]]
  name = "github.com/ChimeraCoder/anaconda"
  version = "2.0.0"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/emersion/go-ostatus"

[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
